# Generated by Django 4.2.1 on 2023-05-13 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание категории')),
                ('image', models.ImageField(upload_to='courses/categories/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер вопроса')),
                ('text', models.TextField(unique=True, verbose_name='Текст вопроса')),
                ('image', models.ImageField(upload_to='courses/questions/', verbose_name='Фото к вопросу')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название курса')),
                ('time', models.CharField(max_length=64, verbose_name='Время прохождения курса')),
                ('image', models.ImageField(upload_to='courses/courses/', verbose_name='Фото к курсу')),
                ('level', models.CharField(choices=[('HIG', 'High'), ('AVG', 'Average'), ('LOW', 'Low')], default='LOW', max_length=3, verbose_name='Уровень сложности курса')),
                ('description', models.TextField(max_length=2048, verbose_name='Описание курса')),
                ('audio', models.FileField(blank=True, upload_to='courses/courses/', verbose_name='Аудио к курсу')),
                ('video', models.URLField(blank=True, help_text='Ссылка на видео', verbose_name='Видео')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['id', 'title'],
            },
        ),
    ]
