# Generated by Django 4.2.1 on 2023-05-13 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Номер вопроса не может быть меньше 1')], verbose_name='Порядковый номер вопроса'),
        ),
    ]
