# Generated by Django 4.2.1 on 2023-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_offlineapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='courses/courses/', verbose_name='Аудио к курсу'),
        ),
    ]
