# Generated by Django 4.2.1 on 2023-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_question_options_alter_course_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audio_description',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Описание аудиокурса'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_description',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Описание видеокурса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='audio',
            field=models.FileField(blank=True, upload_to='courses/courses/', verbose_name='Аудио к курсу'),
        ),
    ]
